# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
    ]
