# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_myuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(default='Noob', max_length=40),
        ),
    ]
