# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qac', '0002_auto_20160403_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
