# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qac', '0003_answer_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
