# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qac', '0004_auto_20160403_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
