# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qac', '0005_auto_20160403_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
